package config

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

// envFrom 把 map 包成 getenv 函数，让配置测试不依赖真实环境变量。
func envFrom(m map[string]string) func(string) string {
	return func(k string) string { return m[k] }
}

// validConfig 返回一份能通过校验的配置。
func validConfig() *Config {
	c := Defaults()
	c.JWTSecret = []byte("0123456789abcdef0123456789abcdef") // 32 字节
	return c
}

func TestDefaultsValidate(t *testing.T) {
	if err := validConfig().Validate(); err != nil {
		t.Fatalf("默认配置应当合法，实际: %v", err)
	}
}

func TestApplyEnvOverrides(t *testing.T) {
	c := Defaults()
	err := c.applyEnv(envFrom(map[string]string{
		"CODEGATE_LISTEN":             "127.0.0.1:9000",
		"CODEGATE_BASE_URL":           "https://cg.example.com/",
		"CODEGATE_DB_PATH":            "/data/cg.db",
		"CODEGATE_JWT_SECRET":         strings.Repeat("x", 40),
		"CODEGATE_ACCESS_TOKEN_TTL":   "5m",
		"CODEGATE_HEARTBEAT_INTERVAL": "10s",
		"CODEGATE_MAX_SESSIONS":       "5",
		"CODEGATE_ALLOW_SIGNUP":       "true",
		"CODEGATE_ALLOWED_ORIGINS":    "https://a.com, https://b.com ,",
		"CODEGATE_LOG_LEVEL":          "debug",
	}))
	if err != nil {
		t.Fatalf("应用环境变量失败: %v", err)
	}

	if c.Listen != "127.0.0.1:9000" {
		t.Errorf("listen 未覆盖: %q", c.Listen)
	}
	// BaseURL 应当去掉末尾斜杠，否则拼出来的链接会出现 `//`。
	if c.BaseURL != "https://cg.example.com" {
		t.Errorf("base_url 应去掉末尾斜杠，实际: %q", c.BaseURL)
	}
	if c.AccessTokenTTL != 5*time.Minute {
		t.Errorf("access ttl 未覆盖: %v", c.AccessTokenTTL)
	}
	if c.HeartbeatInterval != 10*time.Second {
		t.Errorf("heartbeat 未覆盖: %v", c.HeartbeatInterval)
	}
	if c.MaxSessions != 5 {
		t.Errorf("max_sessions 未覆盖: %d", c.MaxSessions)
	}
	if !c.AllowSignup {
		t.Error("allow_signup 未覆盖")
	}
	if len(c.AllowedOrigins) != 2 {
		t.Errorf("origin 列表应过滤空项，实际: %v", c.AllowedOrigins)
	}
	if c.LogLevel != "debug" {
		t.Errorf("log_level 未覆盖: %q", c.LogLevel)
	}
	if err := c.Validate(); err != nil {
		t.Errorf("覆盖后的配置应当合法: %v", err)
	}
}

func TestApplyEnvRejectsBadValues(t *testing.T) {
	cases := []struct {
		name string
		env  map[string]string
	}{
		{"非法时长", map[string]string{"CODEGATE_ACCESS_TOKEN_TTL": "15分钟"}},
		{"非法整数", map[string]string{"CODEGATE_MAX_SESSIONS": "很多"}},
		{"非法布尔", map[string]string{"CODEGATE_ALLOW_SIGNUP": "yes-please"}},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			c := Defaults()
			if err := c.applyEnv(envFrom(tc.env)); err == nil {
				t.Fatal("应当报错，实际通过")
			}
		})
	}
}

// TestValidateCollectsAllProblems 确认校验是「一次报全」而不是「报第一个就返回」。
// 否则用户要改一个跑一次，来回五六轮才能把配置修对。
func TestValidateCollectsAllProblems(t *testing.T) {
	c := Defaults()
	c.JWTSecret = []byte("short") // 太短
	c.Listen = ""
	c.DBPath = ""
	c.LogLevel = "verbose"
	c.PongTimeout = time.Second // 小于 heartbeat_interval

	err := c.Validate()
	if err == nil {
		t.Fatal("应当报错")
	}
	msg := err.Error()
	for _, want := range []string{"listen", "db_path", "jwt secret", "log_level", "pong_timeout"} {
		if !strings.Contains(msg, want) {
			t.Errorf("错误信息里缺少 %q 这一项，实际:\n%s", want, msg)
		}
	}
}

func TestValidateRejectsRefreshShorterThanAccess(t *testing.T) {
	c := validConfig()
	c.AccessTokenTTL = 24 * time.Hour
	c.RefreshTokenTTL = time.Hour
	err := c.Validate()
	if err == nil || !strings.Contains(err.Error(), "refresh_token_ttl") {
		t.Errorf("应当拒绝 refresh <= access，实际: %v", err)
	}
}

func TestValidateRejectsBadBaseURL(t *testing.T) {
	for _, bad := range []string{"ftp://x.com", "not a url", "https://"} {
		c := validConfig()
		c.BaseURL = bad
		if err := c.Validate(); err == nil {
			t.Errorf("base_url=%q 应当被拒绝", bad)
		}
	}
}

func TestOriginAllowed(t *testing.T) {
	c := validConfig()

	// 白名单为空 = 开发模式，放行一切。
	if !c.OriginAllowed("https://evil.example.com") {
		t.Error("白名单为空时应放行")
	}

	c.AllowedOrigins = []string{"https://cg.example.com", "http://localhost:5173"}

	// 大小写与末尾斜杠不应影响判定。
	if !c.OriginAllowed("https://CG.Example.com/") {
		t.Error("应忽略大小写与末尾斜杠")
	}
	if !c.OriginAllowed("http://localhost:5173") {
		t.Error("localhost 应在白名单内")
	}
	if c.OriginAllowed("https://evil.example.com") {
		t.Error("★ 白名单外的 Origin 必须被拒绝（否则等于没有 CSRF 防护）")
	}
	// 空 Origin 放行：非浏览器客户端（curl/测试）没有 cookie 可被 CSRF 利用。
	if !c.OriginAllowed("") {
		t.Error("空 Origin 应放行")
	}
}

func TestSecureCookies(t *testing.T) {
	c := validConfig()
	c.TLS.Enabled = false
	if c.SecureCookies() {
		t.Error("纯 http 不应要求 Secure cookie")
	}

	// 反代终止 TLS 的典型场景：本地 http，对外 https。
	c.BaseURL = "https://cg.example.com"
	if !c.SecureCookies() {
		t.Error("对外 https 时必须要求 Secure cookie")
	}

	c.BaseURL = ""
	c.TLS.Enabled = true
	if !c.SecureCookies() {
		t.Error("启用 TLS 时必须要求 Secure cookie")
	}
}

func TestAutoGeneratedJWTSecretWarns(t *testing.T) {
	c := Defaults()
	if err := c.applyEnv(envFrom(nil)); err != nil {
		t.Fatalf("应用空环境失败: %v", err)
	}
	if len(c.JWTSecret) == 0 {
		t.Fatal("未配置 secret 时应自动生成")
	}
	if len(c.Warnings()) == 0 {
		t.Error("自动生成 secret 必须产生警告，否则生产环境会静默地用上临时密钥")
	}
}

func TestJWTSecretFromFile(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "jwt.secret")
	// 末尾带换行（`echo xxx > file` 的产物），读取时应被 trim 掉。
	if err := os.WriteFile(path, []byte(strings.Repeat("s", 40)+"\n"), 0o600); err != nil {
		t.Fatalf("写文件失败: %v", err)
	}

	c := Defaults()
	err := c.applyEnv(envFrom(map[string]string{"CODEGATE_JWT_SECRET_FILE": path}))
	if err != nil {
		t.Fatalf("读取 secret 文件失败: %v", err)
	}
	if len(c.JWTSecret) != 40 {
		t.Errorf("末尾换行应被去掉，实际长度 %d", len(c.JWTSecret))
	}
}

func TestJWTSecretFileMissing(t *testing.T) {
	c := Defaults()
	err := c.applyEnv(envFrom(map[string]string{
		"CODEGATE_JWT_SECRET_FILE": filepath.Join(t.TempDir(), "nope"),
	}))
	if err == nil {
		t.Fatal("secret 文件不存在时应当报错，而不是静默回落到自动生成")
	}
}

func TestPathsAreNonEmpty(t *testing.T) {
	// 不校验具体值（跨平台不同），只保证不会返回空串导致
	// 后续 filepath.Join 拼出一个诡异的相对路径。
	for name, got := range map[string]string{
		"ConfigDir":       ConfigDir(),
		"DataDir":         DataDir(),
		"DefaultDBPath":   DefaultDBPath(),
		"DefaultKeyPath":  DefaultDeviceKeyPath(),
		"DefaultAgentCfg": DefaultAgentConfigPath(),
	} {
		if strings.TrimSpace(got) == "" {
			t.Errorf("%s 返回了空路径", name)
		}
	}
}

func TestDSHSimpleOriginValidation(t *testing.T) {
	for _, origin := range []string{"https://codegate.example.test", "https://codegate.example.test:443", "http://codegate.example.test:8443", "https://user:password@codegate.example.test:8443", "https://codegate.example.test:8443/path", "https://codegate.example.test:99999"} {
		c := Defaults()
		c.JWTSecret = make([]byte, 32)
		c.BaseURL = "https://codegate.example.test"
		c.DSHProxyURL = origin
		if c.Validate() == nil {
			t.Fatalf("accepted unsafe proxy origin %q", origin)
		}
	}
	c := Defaults()
	c.JWTSecret = make([]byte, 32)
	c.BaseURL = "https://codegate.example.test"
	c.DSHProxyURL = "https://codegate.example.test:8443"
	if err := c.Validate(); err != nil {
		t.Fatal(err)
	}
	c = Defaults()
	if err := c.applyEnv(func(key string) string {
		switch key {
		case "CODEGATE_BASE_URL":
			return "https://codegate.example.test"
		case "CODEGATE_DSH_PROXY_URL":
			return "auto"
		}
		return ""
	}); err != nil {
		t.Fatal(err)
	}
	if c.DSHProxyURL != "https://codegate.example.test:8443" {
		t.Fatal(c.DSHProxyURL)
	}
}
